version: '3'

services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    command: sh -c "cd app && PORT=3000 yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./react:/app
    env_file:
      - .env
