version: '3'

services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: python django/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./django/.env